export const GET_ALL_AUTHORS = 'GET_ALL_AUTHORS';
export const GET_FILTERED_AUTHORS = 'GET_FILTERED_AUTHORS';
export const FILTER_AUTHORS = 'FILTER_AUTHORS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
