export const LOAD_BETWEEN_GET = 'LOAD_BETWEEN_GET';
export const GET_FILTERED_AUTHORS = 'GET_FILTERED_AUTHORS';
export const GET_AUTHORS_BY_ID = 'GET_AUTHORS_BY_ID';
export const GET_FILTERED_TITLES = 'GET_FILTERED_TITLES';
